"""empty message

Revision ID: 0bf2570a97ff
Revises: f5d42d08aad0
Create Date: 2021-06-16 08:13:15.381027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bf2570a97ff'
down_revision = 'f5d42d08aad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assigned_tasks', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('assigned_tasks', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'assigned_tasks', 'task', ['task_id'], ['id'])
    op.create_foreign_key(None, 'assigned_tasks', 'user', ['username'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assigned_tasks', type_='foreignkey')
    op.drop_constraint(None, 'assigned_tasks', type_='foreignkey')
    op.alter_column('assigned_tasks', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('assigned_tasks', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
