"""First snapshot of main database state

Revision ID: 35b6f4f7b2bd
Revises:
Create Date: 2019-11-07 15:48:53.287596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "35b6f4f7b2bd"
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # ### commands auto generated by Alembic ###
    op.create_table(
        "project",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("username", sa.String(length=10), nullable=False),
        sa.Column("firstname", sa.String(), nullable=True),
        sa.Column("surname", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic ###
    op.drop_table("user")
    op.drop_table("project")
    # ### end Alembic commands ###
