"""First snapshot of main database state

Revision ID: 35b6f4f7b2bd
Revises:
Create Date: 2019-11-07 15:48:53.287596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "35b6f4f7b2bd"
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    # TODO: change this for our purpose #
    op.create_table(
        "resources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sa.String(length=10), nullable=True),
        sa.Column("course", sa.String(), nullable=True),
        sa.Column("category", sa.String(length=20), nullable=True),
        sa.Column("type", sa.String(length=4), nullable=True),
        sa.Column("index", sa.Integer(), nullable=True),
        sa.Column("path", sa.String, nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("uploader", sa.String(length=10), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("username", sa.String(length=10), nullable=False),
        sa.Column("firstname", sa.String(), nullable=True),
        sa.Column("surname", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("username"),
    )
    op.create_table(
        "white_list",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("id", "username"),
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("white_list")
    op.drop_table("user")
    op.drop_table("resources")
    # ### end Alembic commands ###
