"""empty message

Revision ID: ca3946ceea1a
Revises: d1228461a0cb
Create Date: 2021-06-10 20:54:00.983912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca3946ceea1a'
down_revision = 'd1228461a0cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('due_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'due_date')
    # ### end Alembic commands ###
