"""empty message

Revision ID: d1228461a0cb
Revises: 8e16378bae7e
Create Date: 2021-06-10 07:54:01.889263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1228461a0cb'
down_revision = '8e16378bae7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assigned_tasks', sa.Column('task_id', sa.Integer(), nullable=True))
    op.add_column('assigned_tasks', sa.Column('username', sa.String(), nullable=True))
    op.add_column('todo', sa.Column('due_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'due_date')
    op.drop_column('assigned_tasks', 'username')
    op.drop_column('assigned_tasks', 'task_id')
    # ### end Alembic commands ###
